# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='precio',
            field=models.CharField(max_length=10),
        ),
    ]
